language: python
dist: xenial
sudo: required
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.7-dev"
    - "pypy"
install:
    - "pip install flake8"
    - "pip install ."
script:
    - "make test"
matrix:
    allow_failures:
        - python: "pypy"
        - python: "3.7"
        - python: "3.7-dev"
